nameOverride: ""
fullnameOverride: ""
images:
  datasetIngest:
    repository: 10.34.25.18/playerone/temp-poc-dataset-ingest
    tag: sha-77a324f98372aeafaec47b0f9d26e2f2fb0d17b6
    digest: sha256:f229785a05b1dc50011bf2bd46f8f85c98cf01e34bab8c0f69e947118faa48da
    sourceRevision: 77a324f98372aeafaec47b0f9d26e2f2fb0d17b6
    pullPolicy: IfNotPresent
  batchAnalyzer:
    repository: 10.34.25.18/playerone/temp-poc-batch-analyzer
    tag: sha-77a324f98372aeafaec47b0f9d26e2f2fb0d17b6
    digest: sha256:8dd6ca85760ff2204ced5def5882e1f26cc16b39c29e18aa98252ca267a57a29
    sourceRevision: 77a324f98372aeafaec47b0f9d26e2f2fb0d17b6
    pullPolicy: IfNotPresent
  reportGenerator:
    repository: 10.34.25.18/playerone/temp-poc-report-generator
    tag: sha-77a324f98372aeafaec47b0f9d26e2f2fb0d17b6
    digest: sha256:92037875d0348823bb2a607a90996c812611c9b7b44b9d1d412035ca2c98ccfc
    sourceRevision: 77a324f98372aeafaec47b0f9d26e2f2fb0d17b6
    pullPolicy: IfNotPresent
datasetIngest:
  replicas: 1
  service:
    port: 80
    annotations:
      scalex.io/exposure: internal
  resources:
    requests:
      cpu: 25m
      memory: 48Mi
    limits:
      cpu: 250m
      memory: 128Mi
batchAnalyzer:
  schedule: "*/2 * * * *"
  datasetUrl: http://10.33.142.20/dataset.csv
  reportUrl: http://10.33.142.21/result
  resources:
    requests:
      cpu: 25m
      memory: 48Mi
    limits:
      cpu: 250m
      memory: 128Mi
reportGenerator:
  replicas: 1
  service:
    port: 80
    annotations:
      scalex.io/exposure: internal
  resources:
    requests:
      cpu: 25m
      memory: 48Mi
    limits:
      cpu: 250m
      memory: 128Mi
karmada:
  enabled: true
  placements:
    datasetIngest:
      cluster: b
      loadBalancerIP: 10.33.142.20
    batchAnalyzer:
      cluster: c
    reportGenerator:
      cluster: b
      loadBalancerIP: 10.33.142.21
