nameOverride: ""
fullnameOverride: ""
images:
  dataset-ingest:
    repository: 10.34.25.18/playerone/temp-poc-dataset-ingest
    tag: v0.1.1
    pullPolicy: IfNotPresent
  batch-analyzer:
    repository: 10.34.25.18/playerone/temp-poc-batch-analyzer
    tag: v0.1.1
    pullPolicy: IfNotPresent
  report-generator:
    repository: 10.34.25.18/playerone/temp-poc-report-generator
    tag: v0.1.1
    pullPolicy: IfNotPresent
datasetIngest:
  replicas: 1
  service:
    port: 80
    annotations:
      scalex.io/exposure: internal
  resources:
    requests:
      cpu: 25m
      memory: 48Mi
    limits:
      cpu: 250m
      memory: 128Mi
batchAnalyzer:
  schedule: "*/2 * * * *"
  datasetUrl: http://10.33.142.20/dataset.csv
  reportUrl: http://10.33.142.21/result
  resources:
    requests:
      cpu: 25m
      memory: 48Mi
    limits:
      cpu: 250m
      memory: 128Mi
reportGenerator:
  replicas: 1
  service:
    port: 80
    annotations:
      scalex.io/exposure: internal
  resources:
    requests:
      cpu: 25m
      memory: 48Mi
    limits:
      cpu: 250m
      memory: 128Mi
karmada:
  enabled: true
  placements:
    datasetIngest:
      cluster: b
      loadBalancerIP: 10.33.142.20
    batchAnalyzer:
      cluster: c
    reportGenerator:
      cluster: b
      loadBalancerIP: 10.33.142.21
