apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "batch-analyzer.fullname" . }}
  labels:
    {{- include "batch-analyzer.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "batch-analyzer.labels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          containers:
            - name: batch-analyzer
              image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
              imagePullPolicy: IfNotPresent
              env:
                - name: FEATURE_CONFIG
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "batch-analyzer.fullname" . }}-config
                      key: FEATURE
                {{- if and .Values.existingSecret.name .Values.existingSecret.key }}
                - name: RUNTIME_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.existingSecret.name | quote }}
                      key: {{ .Values.existingSecret.key | quote }}
                {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
