{{- if .Values.karmada.enabled }}
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: {{ include "temp-poc.fullname" . }}-dataset-ingest
  labels:
    {{- include "temp-poc.labels" . | nindent 4 }}
spec:
  conflictResolution: Abort
  preemption: Never
  priority: 0
  schedulerName: default-scheduler
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: {{ include "temp-poc.fullname" . }}-dataset-ingest
      namespace: {{ .Release.Namespace }}
    - apiVersion: v1
      kind: Service
      name: {{ include "temp-poc.fullname" . }}-dataset-ingest
      namespace: {{ .Release.Namespace }}
  propagateDeps: true
  placement:
    clusterAffinity:
      clusterNames:
        - {{ .Values.karmada.placements.datasetIngest.cluster }}
    spreadConstraints:
      - spreadByField: cluster
        minGroups: 1
        maxGroups: 1
{{- end }}
